package com.group3.vitamins.project.block.infrastructure.persistence;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;

/**
 * 프로젝트 복제(PRJ-018)가 쓰는 쿼리 2개. 파생 메서드명과 JPQL 조인은 <b>컴파일로 안 잡힌다</b> —
 * 이름이 틀리면 부팅 때 터지고, 정렬이 틀리면 예외 없이 배치만 어긋난다.
 */
@DataJpaTest(properties = {
        "spring.flyway.enabled=false",
        "spring.jpa.hibernate.ddl-auto=none"
})
@DisplayName("SpringDataBlockRepository — 복제용 쿼리")
class SpringDataBlockRepositoryCloneQueryTest {

    @Autowired
    private SpringDataBlockRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private static final Long PROJECT_ID = 12L;
    private static final LocalDateTime DELETED_AT = LocalDateTime.of(2026, 8, 13, 10, 0);

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS block");
        jdbcTemplate.execute("DROP TABLE IF EXISTS step");
        jdbcTemplate.execute("""
                CREATE TABLE step (
                    step_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    project_id BIGINT NOT NULL,
                    stage_id BIGINT NULL,
                    name VARCHAR(200) NOT NULL,
                    sort_order INT NOT NULL,
                    version INT NOT NULL DEFAULT 1,
                    started_on DATE NULL,
                    ended_on DATE NULL,
                    owner_user_id VARCHAR(20) NULL,
                    status VARCHAR(20) NOT NULL,
                    completed_at TIMESTAMP NULL,
                    completed_by VARCHAR(20) NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    deleted_at TIMESTAMP NULL
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE block (
                    block_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    step_id BIGINT NOT NULL,
                    title VARCHAR(200) NULL,
                    type VARCHAR(30) NOT NULL,
                    type_id BIGINT NULL,
                    owner VARCHAR(20) NULL,
                    row_index INT NOT NULL,
                    col_span INT NOT NULL,
                    sort_order INT NOT NULL,
                    version INT NOT NULL DEFAULT 1,
                    created_by VARCHAR(20) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    deleted_at TIMESTAMP NULL
                )
                """);
    }

    @Test
    @DisplayName("step 을 조인해 프로젝트의 살아있는 블록만 센다 — 타 프로젝트·삭제분·삭제된 스텝의 블록은 빠진다")
    void countByProjectId() {
        insertStep(1L, PROJECT_ID, false);
        insertStep(2L, PROJECT_ID, false);
        insertStep(3L, PROJECT_ID, true);       // 삭제된 스텝
        insertStep(9L, 99L, false);             // 타 프로젝트

        insertBlock(1L, 0, 1, false);
        insertBlock(1L, 1, 1, false);
        insertBlock(2L, 0, 1, false);
        insertBlock(2L, 0, 2, true);            // 삭제된 블록
        insertBlock(3L, 0, 1, false);           // 삭제된 스텝의 블록
        insertBlock(9L, 0, 1, false);           // 타 프로젝트의 블록

        assertThat(repository.countByProjectId(PROJECT_ID)).isEqualTo(3);
    }

    @Test
    @DisplayName("여러 스텝의 블록을 stepId → rowIndex → sortOrder 순으로 돌려준다 — 삭제분은 빠진다")
    void findByStepIds() {
        insertStep(1L, PROJECT_ID, false);
        insertStep(2L, PROJECT_ID, false);

        // 일부러 뒤섞어 넣는다 — 삽입 순서가 아니라 ORDER BY 가 순서를 정해야 한다
        insertBlock(2L, 0, 1, false);
        insertBlock(1L, 1, 1, false);
        insertBlock(1L, 0, 2, false);
        insertBlock(1L, 0, 1, false);
        insertBlock(1L, 0, 3, true);            // 삭제분

        List<BlockJpaEntity> found = repository
                .findByStepIdInAndDeletedAtIsNullOrderByStepIdAscRowIndexAscSortOrderAsc(
                        Set.of(1L, 2L));

        assertThat(found).extracting(
                        BlockJpaEntity::getStepId,
                        BlockJpaEntity::getRowIndex,
                        BlockJpaEntity::getSortOrder)
                .containsExactly(
                        tuple(1L, 0, 1),
                        tuple(1L, 0, 2),
                        tuple(1L, 1, 1),
                        tuple(2L, 0, 1));
    }

    @Test
    @DisplayName("스텝이 없는 프로젝트는 0 이다 — 조인 결과가 비어도 예외가 아니다")
    void countByProjectId_스텝없음() {
        assertThat(repository.countByProjectId(PROJECT_ID)).isZero();
    }

    private void insertStep(Long stepId, Long projectId, boolean deleted) {
        jdbcTemplate.update("""
                INSERT INTO step (step_id, project_id, name, sort_order, status, deleted_at)
                VALUES (?, ?, ?, ?, 'NOT_STARTED', ?)
                """, stepId, projectId, "스텝" + stepId, stepId.intValue(),
                deleted ? Timestamp.valueOf(DELETED_AT) : null);
    }

    private void insertBlock(Long stepId, int rowIndex, int sortOrder, boolean deleted) {
        jdbcTemplate.update("""
                INSERT INTO block (step_id, type, row_index, col_span, sort_order, created_by, deleted_at)
                VALUES (?, 'TEXT', ?, 1, ?, 'E2024001', ?)
                """, stepId, rowIndex, sortOrder,
                deleted ? Timestamp.valueOf(DELETED_AT) : null);
    }
}
