package com.group3.vitamins.file.infrastructure.persistence;

import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * 낙관락 조건부 UPDATE(§4) 는 순수 Mockito 로는 검증되지 않는다 — 스텁이 반환값을 정해버리기 때문.
 * 실제 H2 로 "버전이 맞을 때만 1행, 어긋나면 0행, 성공 시 version+1" 이 SQL 로 일어나는지 확인한다
 * (issue {@code SpringDataIssueRepositoryTest} 선례).
 */
@DataJpaTest(properties = {
        "spring.flyway.enabled=false",
        "spring.jpa.hibernate.ddl-auto=none"
})
@DisplayName("SpringDataFileRepository — 낙관락 조건부 UPDATE")
class SpringDataFileRepositoryTest {

    @Autowired
    private SpringDataFileRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private EntityManager entityManager;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS file");
        jdbcTemplate.execute("""
                CREATE TABLE file (
                    file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    project_id BIGINT NOT NULL,
                    name VARCHAR(255) NOT NULL,
                    created_by VARCHAR(20) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    version INT NOT NULL DEFAULT 1,
                    deleted_at TIMESTAMP NULL
                )
                """);
    }

    @Test
    @DisplayName("기대 버전이 같을 때만 이름을 바꾸고 버전을 +1 한다 — 어긋나면 0행")
    void renameIfVersionMatches() {
        FileJpaEntity file = saveFile(null);

        // 기대 버전 1 = DB 버전 1 → 성공(1행), DB 버전은 2 가 된다
        assertThat(repository.renameIfVersionMatches(file.getFileId(), "새이름", 1)).isEqualTo(1);
        // 다시 1 로 시도 → 이미 2 라 충돌(0행)
        assertThat(repository.renameIfVersionMatches(file.getFileId(), "덮어쓰기", 1)).isZero();

        entityManager.clear();
        FileJpaEntity updated = repository.findById(file.getFileId()).orElseThrow();
        assertThat(updated.getVersion()).isEqualTo(2);
        assertThat(updated.getName()).isEqualTo("새이름"); // 충돌한 두 번째 저장은 반영되지 않는다
    }

    @Test
    @DisplayName("삭제된 문서는 버전이 맞아도 수정되지 않는다(0행)")
    void skipsDeleted() {
        FileJpaEntity file = saveFile(LocalDateTime.now());

        assertThat(repository.renameIfVersionMatches(file.getFileId(), "새이름", 1)).isZero();
    }

    @Test
    @DisplayName("forceRename 은 버전과 무관하게 무조건 이름을 바꾸고 버전을 +1 한다(덮어쓰기)")
    void forceRename() {
        FileJpaEntity file = saveFile(null); // version 1

        // 기대 버전을 안 걸므로 DB 버전이 뭐든 항상 성공한다
        assertThat(repository.forceRename(file.getFileId(), "강제")).isEqualTo(1);

        entityManager.clear();
        FileJpaEntity updated = repository.findById(file.getFileId()).orElseThrow();
        assertThat(updated.getVersion()).isEqualTo(2);
        assertThat(updated.getName()).isEqualTo("강제");
    }

    @Test
    @DisplayName("forceRename 도 삭제된 문서는 건드리지 않는다(0행)")
    void forceRenameSkipsDeleted() {
        FileJpaEntity file = saveFile(LocalDateTime.now());

        assertThat(repository.forceRename(file.getFileId(), "강제")).isZero();
    }

    private FileJpaEntity saveFile(LocalDateTime deletedAt) {
        // (fileId, projectId, name, createdBy, deletedAt, version)
        return repository.saveAndFlush(new FileJpaEntity(
                null, 100L, "기존이름", "EMP001", deletedAt, 1));
    }
}
