package com.group3.vitamins.issue.infrastructure.persistence;

import com.group3.vitamins.issue.domain.IssuePriority;
import com.group3.vitamins.issue.domain.IssueStatus;
import jakarta.persistence.EntityManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.jdbc.core.JdbcTemplate;

import java.time.LocalDateTime;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest(properties = {
        "spring.flyway.enabled=false",
        "spring.jpa.hibernate.ddl-auto=none"
})
@DisplayName("SpringDataIssueRepository")
class SpringDataIssueRepositoryTest {

    @Autowired
    private SpringDataIssueRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private EntityManager entityManager;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute("DROP TABLE IF EXISTS issue");
        jdbcTemplate.execute("""
                CREATE TABLE issue (
                    issue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title VARCHAR(200),
                    content TEXT,
                    due_date TIMESTAMP NULL,
                    status VARCHAR(20),
                    step_id BIGINT NOT NULL,
                    start_day TIMESTAMP NULL,
                    finish_day TIMESTAMP NULL,
                    priority VARCHAR(20),
                    created_by VARCHAR(20) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    version INT NOT NULL DEFAULT 1,
                    deleted_at TIMESTAMP NULL
                )
                """);
    }

    @Test
    @DisplayName("일반 필드는 기대 버전이 같을 때만 수정하고 버전을 증가시킨다")
    void updateFieldsIfVersionMatches() {
        IssueEntity issue = saveIssue(IssueStatus.TO_DO, null);

        assertThat(repository.updateFieldsIfVersionMatches(
                issue.getIssueId(),
                "수정 제목",
                "수정 내용",
                LocalDateTime.of(2026, 8, 20, 0, 0),
                IssuePriority.HIGH,
                1
        )).isEqualTo(1);
        assertThat(repository.updateFieldsIfVersionMatches(
                issue.getIssueId(),
                "오래된 제목",
                "오래된 내용",
                null,
                IssuePriority.LOW,
                1
        )).isZero();

        entityManager.clear();
        IssueEntity updated = repository.findByIssueIdAndDeletedAtIsNull(issue.getIssueId()).orElseThrow();
        assertThat(updated.getVersion()).isEqualTo(2);
        assertThat(updated.getTitle()).isEqualTo("수정 제목");
        assertThat(updated.getContent()).isEqualTo("수정 내용");
    }

    @Test
    @DisplayName("상태도 기대 버전이 같을 때만 변경하고 완료 시각과 버전을 함께 갱신한다")
    void changeStatusIfVersionMatches() {
        IssueEntity issue = saveIssue(IssueStatus.TO_DO, null);
        LocalDateTime completedAt = LocalDateTime.of(2026, 8, 11, 10, 0);

        assertThat(repository.changeStatusIfVersionMatches(
                issue.getIssueId(), IssueStatus.DONE, completedAt, 1
        )).isEqualTo(1);
        assertThat(repository.changeStatusIfVersionMatches(
                issue.getIssueId(), IssueStatus.IN_PROGRESS, null, 1
        )).isZero();

        entityManager.clear();
        IssueEntity updated = repository.findByIssueIdAndDeletedAtIsNull(issue.getIssueId()).orElseThrow();
        assertThat(updated.getVersion()).isEqualTo(2);
        assertThat(updated.getStatus()).isEqualTo(IssueStatus.DONE);
        assertThat(updated.getFinishDay()).isEqualTo(completedAt);
    }

    @Test
    @DisplayName("관계 전용 수정도 기대 버전이 같을 때만 버전을 증가시킨다")
    void touchIfVersionMatches() {
        IssueEntity issue = saveIssue(IssueStatus.TO_DO, null);

        assertThat(repository.touchIfVersionMatches(issue.getIssueId(), 1)).isEqualTo(1);
        assertThat(repository.touchIfVersionMatches(issue.getIssueId(), 1)).isZero();

        entityManager.clear();
        IssueEntity updated = repository.findByIssueIdAndDeletedAtIsNull(issue.getIssueId()).orElseThrow();
        assertThat(updated.getVersion()).isEqualTo(2);
        assertThat(updated.getTitle()).isEqualTo("기존 제목");
        assertThat(updated.getContent()).isEqualTo("기존 내용");
    }

    private IssueEntity saveIssue(IssueStatus status, LocalDateTime completedAt) {
        return repository.saveAndFlush(new IssueEntity(
                null,
                "기존 제목",
                "기존 내용",
                null,
                status,
                10L,
                null,
                completedAt,
                IssuePriority.MEDIUM,
                "EMP001",
                null,
                null,
                1,
                null
        ));
    }
}
